spring:
  profiles: development
  security:
    user:
      name: user
      password: user
      roles: USER
  datasource:
    driver-class-name: org.postgresql.Driver
    database: org.hibernate.dialect.PostgreSQLDialect
    username: kbandarchyk
    password: 123a456B
    url: jdbc:postgresql://localhost:5432/monitoring_system
    hikari:
      data-source-properties: stringtype=unspecified
  jpa:
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false